version: "3.8"

services:
  api-server:
    image: api-server
    ports:
      - "3000:3000"
    networks:
      - docateste-app
    restart: unless-stopped

  app-client:
    image: app-client
    ports:
      - "8080:80"
    networks:
      - docateste-app

networks:
  docateste-app:
    driver: bridge